version: 2.1

orbs:
  android: circleci/android@0.2.1
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - sonarcloud/scan
      - run:
          command: ./gradlew build
          environment:
            SONARQUBE_SCANNER_PARAMS: '{"sonar.host.url":"https://sonarcloud.io",
              "sonar.projectKey":"OlafusS5_color_timers_kotlin",
              "sonar.organization":"olafuss5"}'
workflows:
  my-workflow:
    jobs:
      - build:
          context: sonarcloud
