version: 2.1

orbs:
  android: circleci/android@0.2.1
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - sonarcloud/scan
      - run:
          command: ./gradlew build
workflows:
  my-workflow:
    jobs:
      - build:
          context: sonarcloud

machine:
  environment:
    BROWSERSTACK_USERNAME: "ondrejkarkoszka1"
    BROWSERSTACK_ACCESS_KEY: "NrcMiiK4GPVZj3dYkdeY"
    BROWSERSTACK_LOCAL: true

test:
  pre:
    # Download the browserstack binary file
    - wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
    # Unzip the BrowserStack Local binary file
    - unzip BrowserStackLocal-linux-x64.zip
    # Run the file with your access key
    - ./BrowserStackLocal $BROWSERSTACK_ACCESS_KEY:
        background: true
